### ISSUE TITLE
Update Tor

### ISSUE THREAD

**Issue by lukechilds** [brunneis/tor-relay-docker#13]
Looks like current latest version supported is Tor 0.4.0.5.

Tor 0.4.0.x will be EOL in a few months (Feb 2, 2020)

https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases#Current

Would be great to get support for current stable releases.

**Comment by lukechilds** [comment]
@brunneis you got a Bitcoin address / LN invoice for a tip?

You can encrypt it with my [PGP key](https://keybase.io/lukechilds/pgp_keys.asc?fingerprint=ea9f04e561a1d10987e3e2e693d612a9d61c281a) or message me on [Keybase](https://keybase.io/lukechilds) if you don't want it public.

**Comment by brunneis** [comment]
Thanks @lukechilds!

My BTC address is `3MeZyYA1ccXcsvSPVQhAq671Tvf9MRmijj`. Very thankful!

**Comment by lukechilds** [comment]
@brunneis you're welcome.

https://blockchair.com/bitcoin/transaction/37bfcf387109fe3aad18f8e4ae7fd888db702f42779f9a8208cf6dad72aa8864

**Comment by brunneis** [comment]
Wow @lukechilds, you were very generous!! Thank you so much! Let's hodl it!
