### ISSUE TITLE
Docker image arch issue for armhf 

### ISSUE THREAD

**Issue by kycfeel** [brunneis/tor-relay-docker#14]
Hi there. Thank you for making an awesome project.

There's one small thing I just notice while trying to run it on my Rpi3.

The docker image for armhf (armv7) is actually built for arm64.

Can you please check it and fix the issue?

Thanks.

![image](https://user-images.githubusercontent.com/22075051/130642819-e3cd00a6-1aba-410e-aa70-8004defebbc7.png)

**Comment by brunneis** [comment]
It should be fixed now. Sorry for the delay in my response @kycfeel.
