### ISSUE TITLE
Add support for IPv6 relays / multiple ORPort configurations

### ISSUE THREAD

**Issue by klamann** [brunneis/tor-relay-docker#5]
I'd like to run an IPv6 relay, because apparently there's not enough IPv6 capable relays online. However, this requires me to set two `ORPort` lines in torrc, like so

    ORPort 9001
    ORPort [2001:DB8::1]:9001

This is also documented in the [Tor relay operators IPv6 HOWTO](https://trac.torproject.org/projects/tor/wiki/doc/IPv6RelayHowto).

Currently, I can only set one such line through the `OR_PORT` environment variable. I'm not sure about the best way to define this, since defining multiple environment variables with the same names is not well-supported... Maybe split at whitespace for just the `OR_PORT` variable? Like so:

    OR_PORT="9001 [2001:DB8::1]:9001"

It's not pretty, but it should do the trick. Anyway, thanks for providing this image :)

**Comment by brunneis** [comment]
Hi @klamann, thank you for your comments. I'll try to take a look at this on the weekend. Anyway, feel free to open a pull request if you want.

**Comment by klamann** [comment]
thanks for solving this :)

**Comment by brunneis** [comment]
Thank you @klamann, does it work now? If so, would you mind giving the repo a star? :)

**Comment by klamann** [comment]
@brunneis yeah, it works great, I can see in the logs how both OR listeners are now started. However, I'm still struggling with the docker ipv6 setup and so far I failed to bind the TOR relay to an address in my ipv6 subnet. Anyway, the solution would work if I'd get my ipv6 setup going ;)

Just for further reference: If you want to get docker and ipv6 running, start here:  
https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6/  
https://collabnix.com/enabling-ipv6-functionality-for-docker-and-docker-compose/  
https://github.com/robbertkl/docker-ipv6nat
