### ISSUE TITLE
Cannot find update-relay.sh in brunneis/tor-relay:x86-64 

### ISSUE THREAD

**Issue by Ryu945** [brunneis/tor-relay-docker#6]
I don't see update script update-relay.sh in build brunneis/tor-relay:x86-64 so I have no way to update the software.  Also, the current version in docker tor-relay-docker (0.3.5.7) gets a complaint that it is out of date.

**Comment by mikahe** [comment]
I'm not an expert here, but it looks like update-relay.sh would need also updated docker image. 

I made a minor change to Dockerfile to update tor tarball version (to ENV TOR_VERSION 0.3.5.8) and created new image with build-arch-images.sh, that seemed to do the trick for me.

**Comment by patzm** [comment]
My understanding is that the `update-relay.sh` helps the maintainer of this repository to regenerate the docker files. Then, the images can be built and pushed to the hub again.
@brunneis what about releasing a new version? There is already `0.4.x` 😄

**Comment by brunneis** [comment]
> My understanding is that the `update-relay.sh` helps the maintainer of this repository to regenerate the docker files. Then, the images can be built and pushed to the hub again.
> @brunneis what about releasing a new version? There is already `0.4.x`

You're right, @patzm. About to release it!

**Comment by Lumies** [comment]
Latest version on Docker hub is 0.4.2.5 which is flagged as not recommended version.
